language: python
python:
  - "2.7"
install: "pip install -r ./util/integration/requirements.txt"
script:
    - py.test -vs ./util/integration/format_tests.py
# safelist
branches:
  only:
  - v3.0/dev
  - v3.0/master
  - v3.1/dev
